Task Management System/Models/ErrorViewModel.cs
using System;

namespace Task_Management_System.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Task Management System/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Task_Management_System.Models;
using TaskManagement.Buisness.Filters;
using TaskManagement.Buisness.ViewModels;

namespace Task_Management_System.Controllers
{
    [AuthorizationFilterAttribute]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Task Management System/Controllers/TaskManagementController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Task_Management_System.Models;
using TaskManagement.Buisness.Filters;
using TaskManagement.Buisness.Interface;
using TaskManagement.Buisness.ViewModels;

namespace Task_Management_System.Controllers
{
    [AuthorizationFilterAttribute]
    public class TaskManagementController : Controller
    {
        private readonly ITaskManagementBuisness taskManagementBuisness;
        public TaskManagementController(ITaskManagementBuisness taskManagementBuisness)
        {
            this.taskManagementBuisness = taskManagementBuisness;
        }
        public async Task<ActionResult> Index()
        {
            TaskManagementFilters taskManagementFilters = new TaskManagementFilters();
            var result = await taskManagementBuisness.GetAllTaskManagement(taskManagementFilters);

            // Get enum values
            var taskStatusValues = Enum.GetValues(typeof(Task_Status))
                                       .Cast<Task_Status>()
                                       .Select(s => new SelectListItem
                                       {
                                           Value = ((int)s).ToString(),
                                           Text = s.ToString()
                                       });

            ViewBag.TaskStatus = taskStatusValues;


            return View(result);
        }
        public ActionResult GetAllTask(TaskManagementFilters taskManagementFilters)
        {
            var tasks = taskManagementBuisness.GetAllTaskManagement(taskManagementFilters);
            return PartialView("_TaskTablePartial", tasks.Result);
        }

        public IActionResult Create()
        {
            return PartialView();
        }
        public async Task<ActionResult> Edit(TaskModel taskModel)
        {
            var taskStatusValues = await taskManagementBuisness.GetTaskByID(taskModel);
            return PartialView("Create", taskStatusValues);
        }


        [HttpPost]
        public async Task<IActionResult> Save(TaskModel taskModel)
        {
            try
            {
                // Perform data validation within the try block
                if (taskModel.Title == null)
                {
                    throw new Exception("Please enter Title");
                }

                string taskDate = taskModel.DueDate.ToString();
                if (taskDate == "01-01-0001 00:00:00")
                {
                    throw new Exception("Please select Due Date"); // Or a custom validation exception
                }

                // Save task using taskManagementBuisness
                var status = await this.taskManagementBuisness.SaveOrUpdate(taskModel);

                return Json(new { IsValid = true, message = "Task Saved successfully!" });
            }
            catch (Exception ex)
            {
                // Handle general exceptions gracefully (e.g., logging, user-friendly message)
                return Json(new { IsValid = false, message = ex.Message });
            }
        }

        public async Task<IActionResult> Delete(TaskModel taskModel)
        {
            try
            {
                var status = await this.taskManagementBuisness.Delete(taskModel);

                return Json(new { IsValid = true, message = "Task Deleted Successfully!" });
            }
            catch (Exception ex)
            {
                return Json(new { IsValid = false, message = ex.Message });
            }


        }
    }
}

Task Management System/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Task Management System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskManagementSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
   </head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TaskManagementSystem</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TaskManagement" asp-action="Index">Tasks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                        </li>
                        <li class="page-header-toolbar-app">
                            <div id="snackbar" class="alert alert-success" style="left:500px;">
                            </div>
                        </li>
                    </ul>

                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TaskManagementSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
    <div class="modal fade" tabindex="-1" role="dialog" id="form-modal">
        <div class="modal-dialog  modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header d-flex justify-content-between ">
                    <h4 class="modal-title">Modal title</h4>
                    <div id="alert-box-app">
                        <p class="text-success"></p>
                        <p class="text-danger"></p>
                        <p class="text-warning"></p>
                        <p class="text-info"></p>
                    </div>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Modal body text goes here.</p>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Task Management System/Views/TaskManagement/Create.cshtml
@model TaskManagement.Buisness.ViewModels.TaskModel


    <form id="formTaskManagement" asp-area="" asp-action="Save" onsubmit="return taskManagement.saveTask(this)">
        <input type="hidden" name="Id" asp-for="@Model.Id" />
        <div class="row form-group">
            <div class="col-sm-3">
                <label asp-for="Title" class="required"></label>
            </div>
            <div class="col-sm-6">
                <input asp-for="Title" class="form-control" />
                @Html.ValidationMessageFor(Model => Model.Title, "", new { @class = "text-danger" })
            </div>

            <div class="col-sm-3  d-flex align-items-center">
                <label class="form-control-label">
                    <input asp-for="Status" type="checkbox" />&nbsp;&nbsp;Is Completed
                </label>
            </div>
        </div>
        <div class="row form-group">
            <div class="col-sm-3">
                <label asp-for="Description" class="required"></label>
            </div>
            <div class="col-sm-9">
                <input asp-for="Description" class="form-control" />
                @Html.ValidationMessageFor(Model => Model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row form-group">
            <div class="col-sm-3">
                <label asp-for="DueDate" class="required"></label>
            </div>
            <div class="col-sm-9">
                <input asp-for="DueDate" class="form-control" />
                @Html.ValidationMessageFor(Model => Model.DueDate, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="modal-footer">
            <button id="btnSubmit" type="submit" class="btn btn-success save-event waves-effect waves-light btn-sm">
                <i class="fa fa-floppy-o" aria-hidden="true"></i> Save
            </button>
        </div>
    </form>

Task Management System/Views/TaskManagement/Index.cshtml
@model IEnumerable<TaskManagement.Buisness.ViewModels.TaskModel>
<link rel="stylesheet" href="~/css/site.css" />
<script src="~/js/TaskManagement.js"></script>
<script src="~/js/site.js"></script>

<div class="row">

</div>
<div class="container">
    <div style=" padding: 60px 0px 0px 0px">
        <div class="row form-group align-items-center">
            <div class="col-sm-1 mt-1">
                <label class="form-control-label">Status </label>
            </div>
            <div class="col-sm-4">
                @Html.DropDownList("status", new SelectList(((dynamic)ViewBag.TaskStatus) ?? new List<dynamic>(), "Value", "Text"), new { @class = "custom-select" })
            </div>
            <div class="col-sm-2 ms-auto">
                <a class="btn btn-success text-white btn-sm" onclick="taskManagement.searchTasks()">Search</a>
            </div>
            <div class="col-sm-2">
                <a onclick="taskManagement.addTask('@Url.Action("Create", "TaskManagement", null, Context.Request.Scheme)', 'Create')"
                   class="btn btn-success text-white btn-sm float-end"> New </a>
            </div>
        </div>
    </div>
    <div>
       
    </div>
    <div>
        <table border="1">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Due Date</th>
                    <th>Status</th>
                    <th style="width:110px;">Actions</th>
                </tr>
            </thead>
            <tbody>
                @Html.Partial("_TaskTablePartial", Model)
            </tbody>
        </table>
    </div>
</div>

Task Management System/Views/TaskManagement/_TaskTablePartial.cshtml
@model IEnumerable<TaskManagement.Buisness.ViewModels.TaskModel>

                    @foreach (var task in Model)
                    {
                        <tr>
                            <td>@task.Title</td>
                            <td>@task.Description</td>
                            <td>@task.DueDate.ToString("dd-MM-yyyy")</td>
                            <td>@task.TaskStatus</td>
                            <td style="width:50px;">
                                <a href="javascript:void(0);" onclick="taskManagement.editTask('@Url.Action("Edit", "TaskManagement", new { id = task.Id })', 'Edit')">
                                    Edit
                                    <i class="fas fa-edit"></i>
                                </a> |
                                <a href="javascript:void(0);" onclick="taskManagement.deleteTask('@Url.Action("Delete", "TaskManagement", new { id = task.Id })')">Delete</a>
                            </td>
                        </tr>
                    }

Task Management System/Views/User/Login.cshtml
@model TaskManagement.Buisness.ViewModels.LoginViewModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{ Layout = ""; }


<link rel="stylesheet" href="~/css/site.css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="~/js/User.js"></script>
<style>
    body {
        background-image: url('~/Image/taskmanagement.png');
        background-size: cover;
        background-position: center;
        background-repeat:no-repeat;
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
        margin: 0;
        padding: 0;
        display: flex;
        align-items: center;
        justify-content: center;
        height: 100vh;
    }
</style>
<body class="body">
    <div class="login-container">
        <!-- Your existing HTML content -->
        <div class="row">
            <div class="col-sm-12 text-center">
                <label class="text-danger" id="errorMessage">@ViewBag.Error</label>
            </div>
        </div>
        <form asp-action="Login" method="post">
            <div class="mt-3">
                <label asp-for="Email">Email:</label>
                <input asp-for="Email" />
                <span asp-validation-for="Email"></span>
            </div>

            <div class="mt-3">
                <label asp-for="Password">Password:</label>
                <input asp-for="Password" type="password" />
                <span asp-validation-for="Password"></span>
            </div>
            <div class="mt-3">
                <button type="submit">Login</button>
            </div>
            <div>
                <p>Don't have an account? <a href="javascript:void(0);" onclick="user.redirectToRegister()">Register Here</a>.</p>
            </div>
        </form>
    </div>
</body>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="~/js/site.js"></script>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

Task Management System/Views/User/Register.cshtml
@model TaskManagement.Buisness.ViewModels.UserModel

@{ Layout = ""; }
<link rel="stylesheet" href="~/css/site.css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<style>
    body {
        background-image: url('file:///C:\Users\axobi\source\repos\Task Management System\Task Management System\wwwroot\Image\taskManagement.png');
        display: flex;
        align-items: center;
        justify-content: center;
        height: 100vh;
        margin: 0;
        background-color: #f5f5f5;
    }
</style>
<div class="form-container">
    <h2>@ViewData["Title"]</h2>
    <div class="text-center">
        <h1>Register</h1>
    </div>

    <form asp-action="Register" method="post">
        <div class="row">
            <div class="col-sm-12 text-center">
                <label class="text-danger" id="errorMessage">@ViewBag.Error</label>
            </div>
        </div>
        <div class="mt-3">
            <label asp-for="Username" class="required">Username:</label>
            <input asp-for="Username" />
            <span asp-validation-for="Username"></span>
        </div>

        <div class="mt-3">
            <label asp-for="Email" class="required">Email:</label>
            <input asp-for="Email" />
            <span asp-validation-for="Email"></span>
        </div>

        <div class="mt-3">
            <label asp-for="Password" class="required">Password:</label>
            <input asp-for="Password" type="password" />
            @*<span asp-validation-for="Password"></span>*@
            @Html.ValidationMessageFor(Model => Model.Password, "", new { @class = "text-danger" })
        </div>

        <div class="mt-3">
            <label asp-for="ConfirmPassword" class="required">Confirm Password:</label>
            <input asp-for="ConfirmPassword" type="password" />
            @*<span asp-validation-for="ConfirmPassword"></span>*@
            @Html.ValidationMessageFor(Model => Model.ConfirmPassword, "", new { @class = "text-danger" })
        </div>

        <div class="mt-3">
            <button type="submit">Register</button>
        </div>
    </form>
</div>